app/main/__init__.py
from flask import Blueprint

main_bp = Blueprint('main', __name__, template_folder='templates')

from . import views

app/main/views.py
from . import main_bp
from app import db
from app.models import Waitlist
from flask import render_template, request, redirect, url_for, current_app, jsonify, flash
import requests
import json


@main_bp.route('/')
def show_index():
    card1 = {
        'imgsrc': "img/dashboard.png",
        'title': 'Intuitive Dashboard',
        'text': 'Manage your projects effortlessly with our user-friendly interface.'
    }
    card2 = {
        'imgsrc': 'img/clientportal.png',
        'title': 'Client Portal',
        'text': 'Allow your clients to view project progress, approve designs, and provide feedback.'
    }
    card3 = {
        'imgsrc': 'img/marketing.png',
        'title': 'Marketing Tools',
        'text': 'Promote your services effectively with customizable marketing templates.'
    }
    card4 = {
        'imgsrc': 'img/education.png',
        'title': 'Learning Center',
        'text': 'Access tutorials and expert advice to improve your landscaping techniques.'
    }
    features = [card1, card2, card3, card4]
    quote1 = {
        'quote': '"All factors go into doing your best to give a quote to the customer, really like, as soon as possible. You know your closing rates are gonna increase most definitely. If you\'re able to give a quote on the spot."',
        'author': 'Rob Fajardo, Trenton Falls, Idaho'
    }
    quote2 = {
        'quote': '"I can\'t wait to see how this platform helps my business grow!"',
        'author': 'John D., Landscaper'
    }
    quotes = [quote1, quote2]
    question1 = {
        'headingId': 'question1',
        'collapseId': 'question1Collapse',
        'question': 'What is OpenSprouts?',
        'answer': 'OpenSprouts is an all-in-one platform designed to help landscapers manage their businesses effectively.'
    }
    question2 = {
        'headingId': 'question2',
        'collapseId': 'question2Collapse',
        'question': 'How does the waitlist work?',
        'answer': 'Sign up now, and you’ll be notified as soon as we launch, gaining early access to our features.'
    }
    question3 = {
        'headingId': 'question3',
        'collapseId': 'question3Collapse',
        'question': 'Is there a cost to join the waitlist?',
        'answer': 'No, signing up for the waitlist is completely free!'
    }
    questions = [question1, question2, question3]
    return render_template('main/index.html', features=features, quotes=quotes, questions=questions, title="Welcome")

@main_bp.route('/waitlist', methods=['POST'])
def add_to_waitlist():
    captcha_response = request.get_json
    if request.method == "POST":
        email = request.form.getlist('email')

        if is_human(captcha_response):
            waitlist_item = Waitlist(email=email)
            db.session.add(waitlist_item)
            db.session.commit()
            status = "Email Saved!"
        else:
            status = "Sorry! Bots are not allowed."
        
        flash(status)
    return redirect(url_for("main.thank_you"))

def is_human(captcha_response):
    secret = current_app.config['CAPTCHA_SECRET_KEY']
    payload = {'response':captcha_response, 'secret':secret}
    response = requests.post("https://www.google.com/recaptcha/api/siteverify", payload)
    response_text = json.loads(response.text)
    return response_text['success']

@main_bp.route('/thank_you')
def thank_you():
    return render_template('main/thank_you.html', title="Thank You")

app/main/templates/main/index.html
{% extends 'base.html' %}

{% block meta %}
<meta name="keywords" content="OpenSprouts, landscaping services, landscaping apps, Landscaping companies near me, Landscaping services near me, Hardscaping near me">
<meta name="robots" content="index,follow">
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/main-index.css') }}">
{% endblock %}

{% block main %}
<div class="px-md-4 py-md-5 text-center hero">
  <div class="text-bg rounded p-3 p-sm-5">
    <h3 class="display-4 fw-bold text-body-emphasis">Transform Your Landscaping Business with OpenSprouts!</h3>
    <div class="container mx-auto">
      <p class="lead mb-4 mx-md-4 text">Join the waitlist for early access to the innovative platform designed for landscapers.</p>
      <form action="{{ url_for('main.add_to_waitlist') }}" method="post">
        <div class="row g-3 align-items-center justify-content-center">
          <div class="col-auto">
            <input name="email" type="email" class="form-control-lg waitlist-input" placeholder="Email Address" aria-label="Email Address" aria-describedby="topBtn" required>
          </div>
          <div class="col-auto mb-3 mb-sm-0">
            <button id="topBtn" type="submit" class="btn btn-primary btn-lg px-4 gap-3">Join the Waitlist Now</button>
          </div>
          <div class="g-recaptcha" data-sitekey="{{ sitekey }}"></div>
        </div>
      </form>
    </div>
  </div>
</div>
<div class="container text-center introduction">
  <h2 class="intro-text mb-4">OpenSprouts is here to revolutionize the way landscapers connect with clients, manage projects, and grow their businesses.</h2>
  <h2 class="intro-text">Whether you're a seasoned pro or just starting, our platform offers tools and resources tailored to your needs.</h2>
</div>
<div class="container-fluid features">
  <div class="container">
    <h2 class="text-center text-white">Features Designed for Landscapers</h2>
  </div>
    <div class="container row py-4 mx-auto">
    {% for feature in features %}
      <div class="col-xl-3 align-self-center card-col">
        <div class="card mx-3 my-3" style="width: 16rem; height: 21rem;">
          <img src="{{ url_for('static', filename=feature.imgsrc) }}" class="card-img-top cardImg mx-auto p-3 align-items-center" alt="{{ feature.title }}">
          <div class="card-body text-center d-flex flex-column">
            <h5 class="card-title mt-auto">{{ feature.title }}</h5>
            <p class="card-text {% if loop.first %}mb-4 {% endif %}">{{ feature.text }}</p>
          </div>
        </div>
      </div>
    {% endfor %}
    </div>
</div>
<div class="container-fluid testimonials mb-5">
  <div class="container text-center mb-3">
    <h1>What People Are Saying</h1>
  </div>
  <div class="container-fluid d-block d-md-none mb-5">
    <div class="row py-4">
      {% for quote in quotes %}
      <div class="col-12 my-3">
        <div class="card">
          <div class="card-body">
            <i><h3 class="card-title quote">{{ quote.quote }}</h5></i>
            <i><h5 class="card-subtitle my-3 text-end text-muted author">&mdash; {{ quote.author }}</h6></i>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
  <div id="carouselFade" class="carousel slide carousel-fade mb-5 d-none d-md-block" data-bs-ride="carousel">
    <div class="carousel-inner container-fluid">
    {% for quote in quotes %}
      <div class="carousel-item {% if loop.first %}active {% endif %} d-grid gap-2 d-sm-flex justify-content-sm-center">
        <div class="card mb-5 carousel-card" style="width: 64rem;">
          <div class="card-body">
            <i><h3 class="card-title quote">{{ quote.quote }}</h5></i>
            <i><h5 class="card-subtitle my-3 text-end text-muted author">&mdash; {{ quote.author }}</h6></i>
          </div>
        </div>
      </div>
    {% endfor %}
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselFade" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true" id="prev-btn"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselFade" data-bs-slide="next" id="next-btn">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</div>
<div class="container-fluid cta p-2 p-md-5 my-md-5">
  <div class="container mx-auto text-center card-bg rounded p-2 my-4 p-md-5 my-md-5">
    <h1>Don’t Miss Out!</h1>
    <div class="container my-4">
      <h4 class="my-4">Be one of the first to experience OpenSprouts and transform your landscaping business.</h4>
      <h4>Sign up for our waitlist today!</h4>
    </div>
    <div class="container">
      <form action="{{ url_for('main.add_to_waitlist') }}" method="post">
        <div class="row g-3 align-items-center justify-content-center">
          <div class="col-auto">
            <input name="email" type="email" class="form-control-lg waitlist-input" placeholder="Email Address" aria-label="Email Address" aria-describedby="bottomBtn" required>
          </div>
          <div class="col-auto">
            <button id="bottomBtn" type="submit" class="btn btn-primary btn-lg px-4 gap-3">Join the Waitlist Now</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
<div class="container-fluid questions mx-auto">
  <div class="container text-center pt-4 mb-5 mt-3">
    <h3>Have Questions?</h3>
  </div>
  <div class="accordion mx-auto" id="accordion">
    {% for question in questions %}
    <div class="accordion-item">
      <h1 class="accordion-header" id="{{ question.headingId }}">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#{{ question.collapseId }}" aria-expanded="false" aria-controls="{{ question.collapseId }}">
          {{ question.question }}
        </button>
      </h1>
      <div id="{{ question.collapseId }}" class="accordion-collapse collapse" aria-labelledby="{{ question.headingId }}" data-bs-parent="#accordion">
        <div class="accordion-body">
          {{ question.answer }}
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

{% block js %}
<script src="{{ url_for('static', filename='js/main.js') }}"></script>
{% endblock %}

app/main/templates/main/thank_you.html
{% extends 'base.html' %}

{% block meta %}
<meta name="robots" content="noindex">
{% endblock%}

{% block css %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/thank-you.css') }}">
{% endblock %}

{% block plugins %}
<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v21.0&appId=1673160769814438"></script>
{% endblock %}

{% block main %}
<div class="container-fluid bg">
    <div class="container white-bg rounded">
        <div class="container text-center mt-3 mt-md-0 mb-md-5">
            <h1>Thank you for joining our waitlist!</h1>
            <p class="larger-text d-none d-sm-block">We’re thrilled to have you on board! Your interest means a lot to us, and we can’t wait to share exciting updates with you!</p>
        </div>
        <div class="container text-center my-3 my-sm-0">
            <h2>What's Next?</h2>
        </div>
        <div class="container d-grid d-sm-flex justify-content-sm-center">
            <ul class="next-list">
                <li><p class="larger-text"><b>Stay Tuned</b>: Keep an eye on your inbox for exclusive sneak peeks and announcements.</p></li>
                <li><p class="larger-text"><b>Spread the Word</b>: Share the excitement with your friends! The more, the merrier.</p></li>
            </ul>
        </div>
        <!-- Share Buttons -->
        <div class="container-fluid text-center share-btns row mb-3 mb-md-5">
            <div class="col col-lg-1 mx-lg-3 mb-2 mb-sm-0">
                <div class="fb-share-button" data-href="https://opensprouts.com" data-layout="button" data-size="large"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fopensprouts.com%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Share</a></div>
            </div>
            <div class="col col-lg-1 mx-lg-3 mb-2 mb-sm-0">
                <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-size="large" data-text="I just joined the waitlist for OpenSprouts! Check it out!" data-url="https://opensprouts.com" data-related="opensprouts" data-lang="en" data-show-count="false">Tweet</a>
            </div>
            <div class="col col-lg-1 mx-lg-3 mb-2 mb-sm-0">
                <a href="https://www.pinterest.com/opensprouts/_created/" data-pin-do="buttonFollow">OpenSprouts</a>
            </div>
            <div class="col col-lg-1 mx-lg-3 mb-2 mb-sm-0">
                <div class="g-ytsubscribe" data-channelid="UCW3EVXSGKipTQ5AImVfQbqg" data-layout="default" data-count="hidden"></div>
            </div>
        </div>
        <!-- End Share Buttons -->
        <div class="container text-center d-none d-md-block">
            <p class="larger-text">If you have any questions or want to connect with us, feel free to reach out.</p>
        </div>
        <div class="container text-center d-none d-md-block">
            <p class="larger-text">Thanks again for being part of our community!</p>
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
<script src="{{ url_for('static', filename='js/waitlist.js') }}"></script>
<script src="https://apis.google.com/js/platform.js"></script>
<script type="text/javascript" async defer src="//assets.pinterest.com/js/pinit.js"></script>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
{% endblock %}