app/models.py
from . import db
from datetime import datetime as dt

# Waitlist Model
class Waitlist(db.Model):
    """ Data model for website waitlist """
    __tablename__ = "waitlist"
    id = db.Column(db.Integer, primary_key=True, unique=True)
    created = db.Column(db.DateTime, index=False, unique=False, nullable=False)
    email = db.Column(db.String(255), index=False, unique=True, nullable=False)

    def __init__(self, email):
        self.email = email
        self.created = dt.now()

    def __repr__(self):
        return f"Waitlist(id={self.id!r}, created={self.created}, email={self.email})"

app/__init__.py
import os
import logging
from flask import Flask, render_template
from flask.logging import default_handler
from flask_sqlalchemy import SQLAlchemy
from logging.handlers import RotatingFileHandler
from jinja2 import ChoiceLoader, FileSystemLoader

db = SQLAlchemy()

def create_app():
    app = Flask(__name__)

    # Configure Flask App Instance
    CONFIG_TYPE = os.getenv('CONFIG_TYPE', default='config.DevelopementConfig')
    app.config.from_object(CONFIG_TYPE)

    # Register blueprints
    register_blueprints(app)
    
    # Initialize flask extension objects
    initialize_extensions(app)
    
    # Configure logging
    configure_logging(app)
    
    # Register error handlers
    register_error_handlers(app)
    
    # Overwrite Flask jinja_loader, using ChoiceLoader
    template_loader = ChoiceLoader([
        app.jinja_loader,
        FileSystemLoader('static'),
    ])

    return app

def register_blueprints(app):
    from app.main import main_bp

    app.register_blueprint(main_bp)

def initialize_extensions(app):
    db.init_app(app)

def register_error_handlers(app):
    pass

def configure_logging(app):
    # Deactivate the default flask logger so that log messages do not get duplicated
    app.logger.removeHandler(default_handler)
    
    # Create a file handler object
    file_handler = RotatingFileHandler('flaskapp.log', maxBytes=16384, backupCount=20)
    
    # Set logging level of file handler object so it logs INFO & up
    file_handler.setLevel(logging.INFO)
    
    # Create file formatter object
    file_formatter = logging.Formatter('%(asctime)s %(levelname)s: %(message)s [in %(filename)s: %(lineno)d]')
    
    # Apply file formatter object to file handler
    file_handler.setFormatter(file_formatter)
    
    # Add file handler to logger
    app.logger.addHandler(file_handler)

app/main/__init__.py
from flask import Blueprint

main_bp = Blueprint('main', __name__, template_folder='templates')

from . import views

app/main/views.py
from . import main_bp
from app import db
from app.models import Waitlist
from flask import render_template, request, redirect, url_for, current_app, jsonify, flash
import requests
import json


@main_bp.route('/')
def show_index():
    card1 = {
        'imgsrc': "img/dashboard.png",
        'title': 'Intuitive Dashboard',
        'text': 'Manage your projects effortlessly with our user-friendly interface.'
    }
    card2 = {
        'imgsrc': 'img/clientportal.png',
        'title': 'Client Portal',
        'text': 'Allow your clients to view project progress, approve designs, and provide feedback.'
    }
    card3 = {
        'imgsrc': 'img/marketing.png',
        'title': 'Marketing Tools',
        'text': 'Promote your services effectively with customizable marketing templates.'
    }
    card4 = {
        'imgsrc': 'img/education.png',
        'title': 'Learning Center',
        'text': 'Access tutorials and expert advice to improve your landscaping techniques.'
    }
    features = [card1, card2, card3, card4]
    quote1 = {
        'quote': '"All factors go into doing your best to give a quote to the customer, really like, as soon as possible. You know your closing rates are gonna increase most definitely. If you\'re able to give a quote on the spot."',
        'author': 'Rob Fajardo, Trenton Falls, Idaho'
    }
    quote2 = {
        'quote': '"I can\'t wait to see how this platform helps my business grow!"',
        'author': 'John D., Landscaper'
    }
    quotes = [quote1, quote2]
    question1 = {
        'headingId': 'question1',
        'collapseId': 'question1Collapse',
        'question': 'What is OpenSprouts?',
        'answer': 'OpenSprouts is an all-in-one platform designed to help landscapers manage their businesses effectively.'
    }
    question2 = {
        'headingId': 'question2',
        'collapseId': 'question2Collapse',
        'question': 'How does the waitlist work?',
        'answer': 'Sign up now, and you’ll be notified as soon as we launch, gaining early access to our features.'
    }
    question3 = {
        'headingId': 'question3',
        'collapseId': 'question3Collapse',
        'question': 'Is there a cost to join the waitlist?',
        'answer': 'No, signing up for the waitlist is completely free!'
    }
    questions = [question1, question2, question3]
    return render_template('main/index.html', features=features, quotes=quotes, questions=questions, title="Welcome")

@main_bp.route('/waitlist', methods=['POST'])
def add_to_waitlist():
    captcha_response = request.get_json
    if request.method == "POST":
        email = request.form.getlist('email')

        if is_human(captcha_response):
            waitlist_item = Waitlist(email=email)
            db.session.add(waitlist_item)
            db.session.commit()
            status = "Email Saved!"
        else:
            status = "Sorry! Bots are not allowed."
        
        flash(status)
    return redirect(url_for("main.thank_you"))

def is_human(captcha_response):
    secret = current_app.config['CAPTCHA_SECRET_KEY']
    payload = {'response':captcha_response, 'secret':secret}
    response = requests.post("https://www.google.com/recaptcha/api/siteverify", payload)
    response_text = json.loads(response.text)
    return response_text['success']

@main_bp.route('/thank_you')
def thank_you():
    return render_template('main/thank_you.html', title="Thank You")

app/templates/402.html
{% extends 'base.html' %}

{% block css %}
  
{% endblock %}

{% block main %}
    <div class="container">
        <h1>Transaction Error</h1>
        <p>The card we tried did not work. Please provide another form of payment. Thank you and have a great day.</p>
    </div>
{% endblock %}

app/templates/405.html
{% extends 'base.html' %}

{% block css %}
  
{% endblock %}

{% block main %}
<div class="container">
    <h1>405</h1>
    <p>Method not allowed...</p>
</div>
{% endblock %}

{% block js %}
  
{% endblock %}

app/templates/base.html
{% from "./macros.html" import nav_link with context %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta name="language" content="English">
  <meta name="title" content="{{ title }} | OpenSprouts">
  <meta name="author" content="OpenSprouts">
  <meta name="description" content="OpenSprouts is the all-in-one landscaper services application.">
  {% block meta %}{% endblock %}
  <title>{{ title }} | OpenSprouts</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}">
  <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='img/apple-touch-icon.png') }}">
  <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='img/favicon-32x32.png') }}">
  <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='img/favicon-16x16.png') }}">
  <link rel="manifest" href="{{ url_for('static', filename='img/site.webmanifest') }}">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
  <!-- Hotjar Tracking Code for https://www.opensprouts.com -->
  <script>
    (function(h,o,t,j,a,r){
      h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
      h._hjSettings={hjid:5175708,hjsv:6};
      a=o.getElementsByTagName('head')[0];
      r=o.createElement('script');r.async=1;
      r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
      a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
  </script>
  <!-- Google Recaptcha Tag -->
  <script src="https://www.google.com/recaptcha/api.js?render=explicit" async defer></script>
  <!-- Google tag (gtag.js) --> 
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-F7M4ZLN18K"></script>
  <script> 
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);} 
    gtag('js', new Date()); 
    gtag('config', 'G-F7M4ZLN18K'); 
  </script>
  {% block css %}{% endblock %}
</head>
<body>
  {% block plugins %}{% endblock %}
  <!-- Header / Navbar Section -->
  <header class="py-2 shadow-sm">
    <div class="container-sm">
      <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
          <a class="navbar-brand d-none d-md-block" href="{{ url_for('main.show_index') }}">
            <img src="{{ url_for('static', filename='img/OpenSproutsHoriztontal.png') }}" height="75px">
          </a>
          <a class="navbar-brand d-block d-md-none" href="{{ url_for('main.show_index') }}">
            <img src="{{ url_for('static', filename='img/OpenSprouts_Vertical.png') }}" height="70px">
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ms-auto">
              <li class="nav-item mx-auto">
                <a class="nav-link" href="https://www.instagram.com/opensprouts?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" target="_blank">
                  <img class="logos" src="{{ url_for('static', filename='img/instagram.png') }}">
                </a>
              </li>
              <li class="nav-item mx-auto">
                <a class="nav-link" href="https://x.com/opensprouts" target="_blank">
                  <img class="logos" src="{{ url_for('static', filename='img/twitter.png') }}">
                </a>
              </li>
              <li class="nav-item mx-auto">
                <a class="nav-link" href="https://www.pinterest.com/opensprouts/" target="_blank">
                  <img class="logos" src="{{ url_for('static', filename='img/pinterest.png') }}">
                </a>
              </li>
              <li class="nav-item mx-auto">
                <a class="nav-link" href="https://www.youtube.com/channel/UCW3EVXSGKipTQ5AImVfQbqg" target="_blank">
                  <img class="logos" src="{{ url_for('static', filename='img/youtube.png') }}">
                </a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </div>
  </header>

  <!-- Main Section -->
  <main role="main" style="min-height: 90vh;">
    {% block main %}{% endblock %}
  </main>

  <!-- Footer Section -->
  <footer class="text-white">
    <div class="container-fluid footer-nav">
      <ul class="nav col justify-content-center align-items-center py-4 px-2">
        <li class="nav-item mx-4">© 2024 OpenSprouts</li>
        <li class="nav-item">Have more questions? Contact us at <a class="email-link" href="mailto:contact@opensprouts.com">contact@opensprouts.com</a></li>
        <li class="nav-item socials">
          <div class="container d-flex">
            <a class="nav-link" href="https://www.instagram.com/opensprouts?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" target="_blank">
              <img class="logos" src="{{ url_for('static', filename='img/instagramWhite.png') }}">
            </a>
            <a class="nav-link" href="https://x.com/opensprouts" target="_blank">
              <img class="logos" src="{{ url_for('static', filename='img/twitterWhite.png') }}">
            </a>
            <a class="nav-link" href="https://www.pinterest.com/opensprouts/" target="_blank">
              <img class="logos" src="{{ url_for('static', filename='img/pinterestWhite.png') }}">
            </a>
            <a class="nav-link" href="https://www.youtube.com/channel/UCW3EVXSGKipTQ5AImVfQbqg" target="_blank">
              <img class="logos" src="{{ url_for('static', filename='img/youtubeWhite.png') }}">
            </a>
          </div>
        </li>
      </ul>
    </div>
  </footer>
  <script async defer src="{{ url_for('static', filename='js/base.js') }}"></script>
  <script async defer src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
  {% block js %}{% endblock %}
  <script async defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>
</html>